version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres_sw
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "4002:8080"
    depends_on:
      - postgres

  backend:
    container_name: backend_sw
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./sw:/code
    ports:
      - "8000:8000"
    env_file: .env
    tty: true
    stdin_open: true
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx
    container_name: nginx_sw
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db: