# Generated by Django 4.0.3 on 2022-04-10 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("height", models.CharField(max_length=255)),
                ("mass", models.CharField(max_length=255)),
                ("hair_color", models.CharField(max_length=255)),
                ("skin_color", models.CharField(max_length=255)),
                ("eye_color", models.CharField(max_length=255)),
                ("birth_year", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("homeworld", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="characters.collection",
                    ),
                ),
            ],
        ),
    ]
